# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import transport_agent_pb2 as transport__agent__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in transport_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FleetServiceStub(object):
    """option python_package = "transport_proto";  <-- REMOVE THIS LINE

    Fleet service: used for driver updates and status queries
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateLocation = channel.unary_unary(
                '/transport.FleetService/UpdateLocation',
                request_serializer=transport__agent__pb2.UpdateLocationRequest.SerializeToString,
                response_deserializer=transport__agent__pb2.UpdateLocationResponse.FromString,
                _registered_method=True)
        self.UpdateStatus = channel.unary_unary(
                '/transport.FleetService/UpdateStatus',
                request_serializer=transport__agent__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=transport__agent__pb2.UpdateStatusResponse.FromString,
                _registered_method=True)
        self.GetBusStatus = channel.unary_unary(
                '/transport.FleetService/GetBusStatus',
                request_serializer=transport__agent__pb2.GetBusStatusRequest.SerializeToString,
                response_deserializer=transport__agent__pb2.GetBusStatusResponse.FromString,
                _registered_method=True)
        self.FleetOverview = channel.unary_unary(
                '/transport.FleetService/FleetOverview',
                request_serializer=transport__agent__pb2.Empty.SerializeToString,
                response_deserializer=transport__agent__pb2.FleetOverviewResponse.FromString,
                _registered_method=True)


class FleetServiceServicer(object):
    """option python_package = "transport_proto";  <-- REMOVE THIS LINE

    Fleet service: used for driver updates and status queries
    """

    def UpdateLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBusStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FleetOverview(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FleetServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateLocation,
                    request_deserializer=transport__agent__pb2.UpdateLocationRequest.FromString,
                    response_serializer=transport__agent__pb2.UpdateLocationResponse.SerializeToString,
            ),
            'UpdateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateStatus,
                    request_deserializer=transport__agent__pb2.UpdateStatusRequest.FromString,
                    response_serializer=transport__agent__pb2.UpdateStatusResponse.SerializeToString,
            ),
            'GetBusStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBusStatus,
                    request_deserializer=transport__agent__pb2.GetBusStatusRequest.FromString,
                    response_serializer=transport__agent__pb2.GetBusStatusResponse.SerializeToString,
            ),
            'FleetOverview': grpc.unary_unary_rpc_method_handler(
                    servicer.FleetOverview,
                    request_deserializer=transport__agent__pb2.Empty.FromString,
                    response_serializer=transport__agent__pb2.FleetOverviewResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.FleetService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.FleetService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FleetService(object):
    """option python_package = "transport_proto";  <-- REMOVE THIS LINE

    Fleet service: used for driver updates and status queries
    """

    @staticmethod
    def UpdateLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.FleetService/UpdateLocation',
            transport__agent__pb2.UpdateLocationRequest.SerializeToString,
            transport__agent__pb2.UpdateLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.FleetService/UpdateStatus',
            transport__agent__pb2.UpdateStatusRequest.SerializeToString,
            transport__agent__pb2.UpdateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBusStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.FleetService/GetBusStatus',
            transport__agent__pb2.GetBusStatusRequest.SerializeToString,
            transport__agent__pb2.GetBusStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FleetOverview(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.FleetService/FleetOverview',
            transport__agent__pb2.Empty.SerializeToString,
            transport__agent__pb2.FleetOverviewResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ask = channel.unary_unary(
                '/transport.AgentService/Ask',
                request_serializer=transport__agent__pb2.AskRequest.SerializeToString,
                response_deserializer=transport__agent__pb2.AskResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=transport__agent__pb2.AskRequest.FromString,
                    response_serializer=transport__agent__pb2.AskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transport.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('transport.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/transport.AgentService/Ask',
            transport__agent__pb2.AskRequest.SerializeToString,
            transport__agent__pb2.AskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
